### PR TITLE
Minor issues

### PR DESCRIPTION
**Pull request by adius**
Hi,

there were some typos and bugs in your code.
I took the liberty to fix them for you. 😉

Well, actually, [Feram] did it.
It’s a tool that we developed to fix our own code.
If you want to use it as well, it’s really simple to integrate:
[feram.io/help/getting-started]

Hope you like it! 😁

[Feram]: http://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

### CODE REVIEW

**Comment by DomT4** [comment]
This technically adheres to Ruby standards but doesn't adhere to Homebrew's, which follows the Rubocop style guide with some customisations, FWIW.

**Comment by adius** [comment]
The `args` and the `:tags` simplifactions look definitely useful!?

**Comment by DomT4** [comment]
You're welcome to discuss it with the person who maintains this tap, I have absolutely no power here. Just saying the changes don't adhere to Homebrew standard, as you can see yourself from the ~4500 examples [here](https://github.com/Homebrew/homebrew-core/tree/master/Formula).

**Comment by drewda** [comment]
Thank you for your contribution, @adius.

Personally, I prefer the contemporary Ruby style of single quotes when not using string interpolation, leaving hashrockets in the past, etc.

But in the context of this repo -- a Homebrew formula -- let's stick with the style enforced by `brew audit --strict https://raw.githubusercontent.com/valhalla/homebrew-valhalla/master/Formula/valhalla.rb`.

If you'd like to propose any functionality changes, please do open a PR at any time!

**Pull request closed without merging**
